"""Automo — automated model optimisation and lifecycle research."""

from ._version import __version__
from .runtime import (
    CrossFitSpec,
    DataInput,
    DataSnapshot,
    DataSource,
    EvaluationContext,
    EvaluationSpec,
    Evaluator,
    FeatureComputer,
    FeatureSetInput,
    FeatureSetSpec,
    FeatureSpec,
    MetricDirection,
    MetricScope,
    MetricSpec,
    ModelGraphSpec,
    ModelNodeSpec,
    ModelOutputBatch,
    ModelOutputInput,
    ModelSpec,
    ModelTrainer,
    ObjectiveSpec,
    ResearchPlugin,
    ResearchRuntime,
    TrainingRequest,
    TrainingResult,
)

__all__ = [
    "CrossFitSpec",
    "DataInput",
    "DataSnapshot",
    "DataSource",
    "EvaluationContext",
    "EvaluationSpec",
    "Evaluator",
    "FeatureComputer",
    "FeatureSetInput",
    "FeatureSetSpec",
    "FeatureSpec",
    "MetricDirection",
    "MetricScope",
    "MetricSpec",
    "ModelGraphSpec",
    "ModelNodeSpec",
    "ModelOutputBatch",
    "ModelOutputInput",
    "ModelSpec",
    "ModelTrainer",
    "ObjectiveSpec",
    "ResearchPlugin",
    "ResearchRuntime",
    "TrainingRequest",
    "TrainingResult",
    "__version__",
]
